version: '3.3'
networks:
  default:
    driver: bridge
    ipam:
      driver: default
services:
  money-xiaolin:
    environment:
      ENV: "production"
      MONGODB_URL: "mongodb://127.0.0.1:27017/money-pro"
      JWT_KEY: "KjTaa2HqWKDKRpkQyhkf"
      REFRESH_KEY: "S9LnEeyiVBJDhHE2mlQkKk"
      SENDGRID_API_KEY: "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"
      EXPIRED_IN: "30 days"
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    container_name: money-xiaolin
    ports:
      - "8888:8888"